// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lestoma.Data;

namespace lestoma.Data.Migrations
{
    [DbContext(typeof(LestomaContext))]
    [Migration("20220807031522_First-Data")]
    partial class FirstData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("lestoma.Entidades.Models.EActividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre_actividad");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("actividad", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 601, DateTimeKind.Local).AddTicks(8022),
                            Ip = "172.25.224.1",
                            Nombre = "control de agua",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("be63bec7-8971-48b7-8385-7aab75c8b01d"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 601, DateTimeKind.Local).AddTicks(8047),
                            Ip = "172.25.224.1",
                            Nombre = "alimentacion de peces",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EAplicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NombreAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("TiempoExpiracionToken")
                        .HasColumnType("smallint")
                        .HasColumnName("tiempo_expiracion_token");

                    b.HasKey("Id");

                    b.ToTable("aplicacion", "seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreAplicacion = "App Movil",
                            TiempoExpiracionToken = (short)31
                        },
                        new
                        {
                            Id = 2,
                            NombreAplicacion = "Web",
                            TiempoExpiracionToken = (short)45
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Accion")
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("PKTabla")
                        .HasColumnType("text")
                        .HasColumnName("pk");

                    b.Property<string>("Schema")
                        .HasColumnType("text")
                        .HasColumnName("schema");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("Tabla")
                        .HasColumnType("text")
                        .HasColumnName("tabla");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<string>("UsuarioBD")
                        .HasColumnType("text")
                        .HasColumnName("user_bd");

                    b.HasKey("Id");

                    b.ToTable("auditoria", "seguridad");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EBuzon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("jsonb")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("buzon", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EComponenteLaboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("JsonEstadoComponente")
                        .HasColumnType("jsonb")
                        .HasColumnName("descripcion_estado");

                    b.Property<Guid>("ModuloComponenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_componente_id");

                    b.Property<string>("NombreComponente")
                        .HasColumnType("text")
                        .HasColumnName("nombre_componente");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<Guid>("UpaId")
                        .HasColumnType("uuid")
                        .HasColumnName("upa_id");

                    b.HasKey("Id");

                    b.HasIndex("ModuloComponenteId");

                    b.HasIndex("UpaId");

                    b.ToTable("componente_laboratorio", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49b17244-255e-4411-a2e4-1dc7211d922d"),
                            ActividadId = new Guid("be63bec7-8971-48b7-8385-7aab75c8b01d"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(928),
                            Ip = "172.25.224.1",
                            JsonEstadoComponente = "{\"Id\":\"da39353a-e5c4-408a-a8f6-240bc15790f5\",\"TipoEstado\":\"ON-OFF\",\"TercerByteTrama\":\"F0\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = new Guid("68d80433-a30f-46a8-9751-fa66a4df652f"),
                            NombreComponente = "BOMBA DE OXIGENO",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac")
                        },
                        new
                        {
                            Id = new Guid("751ef5ec-cc5c-47d0-9fdc-058ce088e71d"),
                            ActividadId = new Guid("be63bec7-8971-48b7-8385-7aab75c8b01d"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(967),
                            Ip = "172.25.224.1",
                            JsonEstadoComponente = "{\"Id\":\"da39353a-e5c4-408a-a8f6-240bc15790f5\",\"TipoEstado\":\"ON-OFF\",\"TercerByteTrama\":\"F0\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = new Guid("68d80433-a30f-46a8-9751-fa66a4df652f"),
                            NombreComponente = "LUZ ESTANQUE",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac")
                        },
                        new
                        {
                            Id = new Guid("6aa9f3fe-be72-48df-b327-a18c2c68e7c8"),
                            ActividadId = new Guid("be63bec7-8971-48b7-8385-7aab75c8b01d"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(993),
                            Ip = "172.25.224.1",
                            JsonEstadoComponente = "{\"Id\":\"da39353a-e5c4-408a-a8f6-240bc15790f5\",\"TipoEstado\":\"ON-OFF\",\"TercerByteTrama\":\"F0\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = new Guid("68d80433-a30f-46a8-9751-fa66a4df652f"),
                            NombreComponente = "DOSIFICADOR DE ALIMENTO",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac")
                        },
                        new
                        {
                            Id = new Guid("cba16d2d-259b-407a-96a2-6a969e4a3532"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(998),
                            Ip = "172.25.224.1",
                            JsonEstadoComponente = "{\"Id\":\"f7c21379-5977-4210-9651-fd5de7af4a5b\",\"TipoEstado\":\"LECTURA\",\"TercerByteTrama\":\"0F\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = new Guid("78049990-d5ba-481f-aa21-d23b444ad918"),
                            NombreComponente = "TEMPERATURA H2O",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac")
                        },
                        new
                        {
                            Id = new Guid("7a2b6285-f5dd-4c16-be40-4dbabd4246e3"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(1001),
                            Ip = "172.25.224.1",
                            JsonEstadoComponente = "{\"Id\":\"f7c21379-5977-4210-9651-fd5de7af4a5b\",\"TipoEstado\":\"LECTURA\",\"TercerByteTrama\":\"0F\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = new Guid("78049990-d5ba-481f-aa21-d23b444ad918"),
                            NombreComponente = "PH",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac")
                        },
                        new
                        {
                            Id = new Guid("d62d15c6-f5a7-4b80-9054-9f2b035a48e9"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(1006),
                            Ip = "172.25.224.1",
                            JsonEstadoComponente = "{\"Id\":\"f7c21379-5977-4210-9651-fd5de7af4a5b\",\"TipoEstado\":\"LECTURA\",\"TercerByteTrama\":\"0F\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = new Guid("78049990-d5ba-481f-aa21-d23b444ad918"),
                            NombreComponente = "NIVEL TANQUE",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac")
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EEstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DescripcionEstado")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("estado_usuario", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescripcionEstado = "verificar cuenta"
                        },
                        new
                        {
                            Id = 2,
                            DescripcionEstado = "Activado"
                        },
                        new
                        {
                            Id = 3,
                            DescripcionEstado = "Inactivo"
                        },
                        new
                        {
                            Id = 4,
                            DescripcionEstado = "Bloqueado"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ELaboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComponenteLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("componente_laboratorio_id");

                    b.Property<bool>("EstadoInternet")
                        .HasColumnType("boolean")
                        .HasColumnName("estado_internet");

                    b.Property<DateTime>("FechaCreacionDispositivo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_dispositivo");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<double?>("SetPoint")
                        .HasColumnType("double precision")
                        .HasColumnName("set_point");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<int>("TipoDeComunicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_com_id");

                    b.Property<string>("TramaEnviada")
                        .HasColumnType("text")
                        .HasColumnName("trama_enviada");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteLaboratorioId");

                    b.HasIndex("TipoDeComunicacionId");

                    b.ToTable("detalle_laboratorio", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94a97b5f-996c-41d5-b172-538b3efe9e32"),
                            ComponenteLaboratorioId = new Guid("49b17244-255e-4411-a2e4-1dc7211d922d"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(4252),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(4239),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 1,
                            TramaEnviada = "4901F000000000006180"
                        },
                        new
                        {
                            Id = new Guid("0d2ce4e4-5ebb-4601-8972-b5fe6a4f5004"),
                            ComponenteLaboratorioId = new Guid("751ef5ec-cc5c-47d0-9fdc-058ce088e71d"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(5967),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 630, DateTimeKind.Local).AddTicks(5956),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 2,
                            TramaEnviada = "6F01F000000000005302"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EModuloComponente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre_modulo");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("modulo_componente", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68d80433-a30f-46a8-9751-fa66a4df652f"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 562, DateTimeKind.Local).AddTicks(2401),
                            Ip = "172.25.224.1",
                            Nombre = "ACTUADORES",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("78049990-d5ba-481f-aa21-d23b444ad918"),
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 564, DateTimeKind.Local).AddTicks(7896),
                            Ip = "172.25.224.1",
                            Nombre = "SENSORES",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EProtocoloCOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PrimerByteTrama")
                        .HasColumnType("text")
                        .HasColumnName("primer_byte_trama");

                    b.Property<string>("Sigla")
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.ToTable("protocolo_com", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Peer to Peer",
                            PrimerByteTrama = "49",
                            Sigla = "PP"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Broad Cast",
                            PrimerByteTrama = "6F",
                            Sigla = "BS"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ERol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_rol");

                    b.HasKey("Id");

                    b.ToTable("rol", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreRol = "Super Administrador"
                        },
                        new
                        {
                            Id = 2,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            NombreRol = "Auxiliar"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ESuperAdministrador", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<short>("UsuarioId")
                        .HasColumnType("smallint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("super_administrador", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            UsuarioId = (short)1
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("CantidadActividades")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad_actividades");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre_upa");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<int>("SuperAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("superadmin_id");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("upa", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac"),
                            CantidadActividades = (short)5,
                            Descripcion = "queda ubicada en facatativá",
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 601, DateTimeKind.Local).AddTicks(5732),
                            Ip = "172.25.224.1",
                            Nombre = "finca el vergel",
                            Session = "Anonimo",
                            SuperAdminId = 1,
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("efb96939-d8d1-455d-9efd-bf345ba43732"),
                            CantidadActividades = (short)2,
                            Descripcion = "queda ubicada en la universidad cundinamarca extensión nfaca",
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 601, DateTimeKind.Local).AddTicks(5758),
                            Ip = "172.25.224.1",
                            Nombre = "ucundinamarca",
                            Session = "Anonimo",
                            SuperAdminId = 1,
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpaActividad", b =>
                {
                    b.Property<Guid>("UpaId")
                        .HasColumnType("uuid")
                        .HasColumnName("upa_id");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("UpaId", "ActividadId", "UsuarioId");

                    b.HasIndex("ActividadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("upa_actividad", "superadmin");

                    b.HasData(
                        new
                        {
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            UsuarioId = 2,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 602, DateTimeKind.Local).AddTicks(2066),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac"),
                            ActividadId = new Guid("be63bec7-8971-48b7-8385-7aab75c8b01d"),
                            UsuarioId = 2,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 602, DateTimeKind.Local).AddTicks(2082),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            UsuarioId = 3,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 602, DateTimeKind.Local).AddTicks(2086),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("6e1cb560-1047-4f98-8e2f-e2e57c93f8ac"),
                            ActividadId = new Guid("be63bec7-8971-48b7-8385-7aab75c8b01d"),
                            UsuarioId = 4,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 602, DateTimeKind.Local).AddTicks(2088),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("efb96939-d8d1-455d-9efd-bf345ba43732"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            UsuarioId = 2,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 602, DateTimeKind.Local).AddTicks(2091),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("efb96939-d8d1-455d-9efd-bf345ba43732"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            UsuarioId = 3,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 602, DateTimeKind.Local).AddTicks(2095),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("efb96939-d8d1-455d-9efd-bf345ba43732"),
                            ActividadId = new Guid("bf984295-6d23-42f9-a790-d567b540ccaf"),
                            UsuarioId = 4,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 602, DateTimeKind.Local).AddTicks(2098),
                            Ip = "172.25.224.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoRecuperacion")
                        .HasColumnType("text")
                        .HasColumnName("codigo_recuperacion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<DateTime?>("FechaVencimientoCodigo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("vencimiento_codigo_recuperacion");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("semilla");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Lestoma",
                            Clave = "3RVoU8PlKLRj1bgpxI1ippv6ZfGvfrUwVhLTLkCt/Xw=",
                            Email = "diegop177@hotmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 584, DateTimeKind.Local).AddTicks(6693),
                            Ip = "172.25.224.1",
                            Nombre = "Super Admin",
                            RolId = 1,
                            Salt = "SfhvDub9d7Pm/3skIvAtiQ==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Lestoma",
                            Clave = "v4bDfOL0aR0xJZ98MwaDFBZo7ebyEbL33d9mykAMz1g=",
                            Email = "diegoarturo1598@hotmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 592, DateTimeKind.Local).AddTicks(7510),
                            Ip = "172.25.224.1",
                            Nombre = "Administrador",
                            RolId = 2,
                            Salt = "bA6SLT8feXPi23ZCL3ygBA==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Lestoma",
                            Clave = "PNx6FbHdF+e8d/7j17B6Q0mhvKgNxJxPCOGCveXwO2k=",
                            Email = "programadoresuc@outlook.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 600, DateTimeKind.Local).AddTicks(7975),
                            Ip = "172.25.224.1",
                            Nombre = "Auxiliar 1",
                            RolId = 3,
                            Salt = "DfxeXsg5YFHzTxmRTXGtzA==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Lestoma",
                            Clave = "PNx6FbHdF+e8d/7j17B6Q0mhvKgNxJxPCOGCveXwO2k=",
                            Email = "auxiliar2@gmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 8, 6, 22, 15, 21, 600, DateTimeKind.Local).AddTicks(8002),
                            Ip = "172.25.224.1",
                            Nombre = "Auxiliar 2",
                            RolId = 3,
                            Salt = "DfxeXsg5YFHzTxmRTXGtzA==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EAlimentarPeces", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("alimentar_peces", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlAgua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_de_agua", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlElectrico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_electrico", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlEntorno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_de_entorno", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlHidroponico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_hidroponico", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.ERecirculacionAgua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("recirculacion_de_agua", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EComponenteLaboratorio", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EModuloComponente", "ModuloComponente")
                        .WithMany()
                        .HasForeignKey("ModuloComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUpa", "Upa")
                        .WithMany()
                        .HasForeignKey("UpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuloComponente");

                    b.Navigation("Upa");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ELaboratorio", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EComponenteLaboratorio", "ComponenteLaboratorio")
                        .WithMany()
                        .HasForeignKey("ComponenteLaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EProtocoloCOM", "TipoDeComunicacion")
                        .WithMany()
                        .HasForeignKey("TipoDeComunicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponenteLaboratorio");

                    b.Navigation("TipoDeComunicacion");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpaActividad", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EActividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUpa", "Upa")
                        .WithMany()
                        .HasForeignKey("UpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Upa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUsuario", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EEstadoUsuario", "EstadoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.ERol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("lestoma.Entidades.Models.ETokensUsuarioByAplicacion", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("AplicacionId")
                                .HasColumnType("integer")
                                .HasColumnName("aplicacion_id");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("fecha_creacion");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text")
                                .HasColumnName("creado_por_ip");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("expiracion");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text")
                                .HasColumnName("reeemplazado_por_token");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("fecha_revocacion");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text")
                                .HasColumnName("revocado_por_ip");

                            b1.Property<string>("Token")
                                .HasColumnType("text")
                                .HasColumnName("token");

                            b1.Property<int>("usuario_id")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("usuario_id");

                            b1.ToTable("tokens_usuario_por_aplicacion", "seguridad");

                            b1.WithOwner()
                                .HasForeignKey("usuario_id");
                        });

                    b.Navigation("EstadoUsuario");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EEstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ERol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
