// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lestoma.Data;

namespace lestoma.Data.Migrations
{
    [DbContext(typeof(LestomaContext))]
    [Migration("20220726020938_initial-data")]
    partial class initialdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("lestoma.Entidades.Models.EActividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre_actividad");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("actividad", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(4155),
                            Ip = "10.212.135.7",
                            Nombre = "control de agua",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("c04ef552-5ac2-4df9-8d7b-98897d7e6295"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(4180),
                            Ip = "10.212.135.7",
                            Nombre = "alimentacion de peces",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EAplicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NombreAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("TiempoExpiracionToken")
                        .HasColumnType("smallint")
                        .HasColumnName("tiempo_expiracion_token");

                    b.HasKey("Id");

                    b.ToTable("aplicacion", "seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreAplicacion = "App Movil",
                            TiempoExpiracionToken = (short)31
                        },
                        new
                        {
                            Id = 2,
                            NombreAplicacion = "Web",
                            TiempoExpiracionToken = (short)45
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Accion")
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("PKTabla")
                        .HasColumnType("text")
                        .HasColumnName("pk");

                    b.Property<string>("Schema")
                        .HasColumnType("text")
                        .HasColumnName("schema");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("Tabla")
                        .HasColumnType("text")
                        .HasColumnName("tabla");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<string>("UsuarioBD")
                        .HasColumnType("text")
                        .HasColumnName("user_bd");

                    b.HasKey("Id");

                    b.ToTable("auditoria", "seguridad");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EBuzon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("jsonb")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("buzon", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EComponenteLaboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("JsonEstadoComponente")
                        .HasColumnType("jsonb")
                        .HasColumnName("descripcion_estado");

                    b.Property<int>("ModuloComponenteId")
                        .HasColumnType("integer")
                        .HasColumnName("modulo_componente_id");

                    b.Property<string>("NombreComponente")
                        .HasColumnType("text")
                        .HasColumnName("nombre_componente");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<Guid>("UpaId")
                        .HasColumnType("uuid")
                        .HasColumnName("upa_id");

                    b.HasKey("Id");

                    b.HasIndex("ModuloComponenteId");

                    b.HasIndex("UpaId");

                    b.ToTable("componente_laboratorio", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a933497c-b8e5-4aac-9b1f-5b10414c082f"),
                            ActividadId = new Guid("c04ef552-5ac2-4df9-8d7b-98897d7e6295"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 591, DateTimeKind.Local).AddTicks(9840),
                            Ip = "10.212.135.7",
                            JsonEstadoComponente = "{\"Id\":\"97509b12-d877-4bac-bdde-a2c81dc7fcef\",\"TipoEstado\":\"ON-OFF\",\"TercerByteTrama\":\"F0\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = 1,
                            NombreComponente = "BOMBA DE OXIGENO",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a")
                        },
                        new
                        {
                            Id = new Guid("bf9a5b1b-fe68-41e5-bd6e-38592e337fbf"),
                            ActividadId = new Guid("c04ef552-5ac2-4df9-8d7b-98897d7e6295"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 591, DateTimeKind.Local).AddTicks(9879),
                            Ip = "10.212.135.7",
                            JsonEstadoComponente = "{\"Id\":\"97509b12-d877-4bac-bdde-a2c81dc7fcef\",\"TipoEstado\":\"ON-OFF\",\"TercerByteTrama\":\"F0\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = 1,
                            NombreComponente = "LUZ ESTANQUE",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a")
                        },
                        new
                        {
                            Id = new Guid("65777bf9-6e21-4f44-bef3-afed0e2860d8"),
                            ActividadId = new Guid("c04ef552-5ac2-4df9-8d7b-98897d7e6295"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 591, DateTimeKind.Local).AddTicks(9884),
                            Ip = "10.212.135.7",
                            JsonEstadoComponente = "{\"Id\":\"97509b12-d877-4bac-bdde-a2c81dc7fcef\",\"TipoEstado\":\"ON-OFF\",\"TercerByteTrama\":\"F0\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = 1,
                            NombreComponente = "DOSIFICADOR DE ALIMENTO",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a")
                        },
                        new
                        {
                            Id = new Guid("a0affd81-5be5-4a76-8e66-2007214f14b1"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 591, DateTimeKind.Local).AddTicks(9889),
                            Ip = "10.212.135.7",
                            JsonEstadoComponente = "{\"Id\":\"e0ac82fe-5c64-48d6-8d43-6158df589b26\",\"TipoEstado\":\"LECTURA\",\"TercerByteTrama\":\"0F\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = 2,
                            NombreComponente = "TEMPERATURA H2O",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a")
                        },
                        new
                        {
                            Id = new Guid("c61b76d1-636a-458e-899d-1c62deac672a"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 591, DateTimeKind.Local).AddTicks(9893),
                            Ip = "10.212.135.7",
                            JsonEstadoComponente = "{\"Id\":\"e0ac82fe-5c64-48d6-8d43-6158df589b26\",\"TipoEstado\":\"LECTURA\",\"TercerByteTrama\":\"0F\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = 2,
                            NombreComponente = "PH",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a")
                        },
                        new
                        {
                            Id = new Guid("0618f64b-cf4c-4569-b8be-b0306eea76ac"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 591, DateTimeKind.Local).AddTicks(9921),
                            Ip = "10.212.135.7",
                            JsonEstadoComponente = "{\"Id\":\"e0ac82fe-5c64-48d6-8d43-6158df589b26\",\"TipoEstado\":\"LECTURA\",\"TercerByteTrama\":\"0F\",\"CuartoByteTrama\":\"00\"}",
                            ModuloComponenteId = 2,
                            NombreComponente = "NIVEL TANQUE",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a")
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EEstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DescripcionEstado")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("estado_usuario", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescripcionEstado = "verificar cuenta"
                        },
                        new
                        {
                            Id = 2,
                            DescripcionEstado = "Activado"
                        },
                        new
                        {
                            Id = 3,
                            DescripcionEstado = "Inactivo"
                        },
                        new
                        {
                            Id = 4,
                            DescripcionEstado = "Bloqueado"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ELaboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComponenteLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("componente_laboratorio_id");

                    b.Property<bool>("EstadoInternet")
                        .HasColumnType("boolean")
                        .HasColumnName("estado_internet");

                    b.Property<DateTime>("FechaCreacionDispositivo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_dispositivo");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<double?>("SetPoint")
                        .HasColumnType("double precision")
                        .HasColumnName("set_point");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<int>("TipoDeComunicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_com_id");

                    b.Property<string>("TramaEnviada")
                        .HasColumnType("text")
                        .HasColumnName("trama_enviada");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteLaboratorioId");

                    b.HasIndex("TipoDeComunicacionId");

                    b.ToTable("detalle_laboratorio", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96d219da-7751-428b-a80f-53b3e552183e"),
                            ComponenteLaboratorioId = new Guid("a933497c-b8e5-4aac-9b1f-5b10414c082f"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2022, 7, 25, 21, 9, 37, 592, DateTimeKind.Local).AddTicks(3375),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 592, DateTimeKind.Local).AddTicks(3360),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 1,
                            TramaEnviada = "4901F000000000006180"
                        },
                        new
                        {
                            Id = new Guid("57a115f0-0604-4d57-b69e-e63b44ebd600"),
                            ComponenteLaboratorioId = new Guid("bf9a5b1b-fe68-41e5-bd6e-38592e337fbf"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2022, 7, 25, 21, 9, 37, 592, DateTimeKind.Local).AddTicks(4994),
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 592, DateTimeKind.Local).AddTicks(4981),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 2,
                            TramaEnviada = "6F01F000000000005302"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EModuloComponente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre_modulo");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("modulo_componente", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 541, DateTimeKind.Local).AddTicks(3901),
                            Ip = "10.212.135.7",
                            Nombre = "ACTUADORES",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 543, DateTimeKind.Local).AddTicks(743),
                            Ip = "10.212.135.7",
                            Nombre = "SENSORES",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EProtocoloCOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PrimerByteTrama")
                        .HasColumnType("text")
                        .HasColumnName("primer_byte_trama");

                    b.Property<string>("Sigla")
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.ToTable("protocolo_com", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Peer to Peer",
                            PrimerByteTrama = "49",
                            Sigla = "PP"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Broad Cast",
                            PrimerByteTrama = "6F",
                            Sigla = "BS"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ERol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_rol");

                    b.HasKey("Id");

                    b.ToTable("rol", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreRol = "Super Administrador"
                        },
                        new
                        {
                            Id = 2,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            NombreRol = "Auxiliar"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ESuperAdministrador", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<short>("UsuarioId")
                        .HasColumnType("smallint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("super_administrador", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            UsuarioId = (short)1
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("CantidadActividades")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad_actividades");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre_upa");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<int>("SuperAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("superadmin_id");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("upa", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a"),
                            CantidadActividades = (short)5,
                            Descripcion = "queda ubicada en facatativá",
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(1718),
                            Ip = "10.212.135.7",
                            Nombre = "finca el vergel",
                            Session = "Anonimo",
                            SuperAdminId = 1,
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("4b489e27-ece0-41db-a6a3-a86d659f1de4"),
                            CantidadActividades = (short)2,
                            Descripcion = "queda ubicada en la universidad cundinamarca extensión nfaca",
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(1752),
                            Ip = "10.212.135.7",
                            Nombre = "ucundinamarca",
                            Session = "Anonimo",
                            SuperAdminId = 1,
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpaActividad", b =>
                {
                    b.Property<Guid>("UpaId")
                        .HasColumnType("uuid")
                        .HasColumnName("upa_id");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("UpaId", "ActividadId", "UsuarioId");

                    b.HasIndex("ActividadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("upa_actividad", "superadmin");

                    b.HasData(
                        new
                        {
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            UsuarioId = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(8149),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a"),
                            ActividadId = new Guid("c04ef552-5ac2-4df9-8d7b-98897d7e6295"),
                            UsuarioId = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(8167),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            UsuarioId = 3,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(8172),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("f0fd706b-6913-4cee-b433-b4a63e7ec51a"),
                            ActividadId = new Guid("c04ef552-5ac2-4df9-8d7b-98897d7e6295"),
                            UsuarioId = 4,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(8175),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("4b489e27-ece0-41db-a6a3-a86d659f1de4"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            UsuarioId = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(8178),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("4b489e27-ece0-41db-a6a3-a86d659f1de4"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            UsuarioId = 3,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(8182),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("4b489e27-ece0-41db-a6a3-a86d659f1de4"),
                            ActividadId = new Guid("14938fd4-42dc-4e53-99bf-6f16be59b4d6"),
                            UsuarioId = 4,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 572, DateTimeKind.Local).AddTicks(8184),
                            Ip = "10.212.135.7",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoRecuperacion")
                        .HasColumnType("text")
                        .HasColumnName("codigo_recuperacion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<DateTime?>("FechaVencimientoCodigo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("vencimiento_codigo_recuperacion");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("semilla");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Lestoma",
                            Clave = "oXDvGpj1612barpNvxwfbv36HIlRvqeZrRnHSUa0AzM=",
                            Email = "diegop177@hotmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 555, DateTimeKind.Local).AddTicks(5603),
                            Ip = "10.212.135.7",
                            Nombre = "Super Admin",
                            RolId = 1,
                            Salt = "M57TAJBuPu9lO00CWSMRYQ==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Lestoma",
                            Clave = "wKt45yvYJWmjB5+LoI6QWRx+MIQt5fCppGvfbeYpUY0=",
                            Email = "diegoarturo1598@hotmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 563, DateTimeKind.Local).AddTicks(6124),
                            Ip = "10.212.135.7",
                            Nombre = "Administrador",
                            RolId = 2,
                            Salt = "zZYq+Chup+FSDLV4Zv+IfA==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Lestoma",
                            Clave = "gxs6YWr5hsiOXWDbQhQbUut+nehqfQvItlx6e2R8db8=",
                            Email = "programadoresuc@outlook.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 571, DateTimeKind.Local).AddTicks(3510),
                            Ip = "10.212.135.7",
                            Nombre = "Auxiliar 1",
                            RolId = 3,
                            Salt = "zYszfTg4A0Kw/vODue5eHw==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Lestoma",
                            Clave = "gxs6YWr5hsiOXWDbQhQbUut+nehqfQvItlx6e2R8db8=",
                            Email = "auxiliar2@gmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2022, 7, 25, 21, 9, 37, 571, DateTimeKind.Local).AddTicks(3525),
                            Ip = "10.212.135.7",
                            Nombre = "Auxiliar 2",
                            RolId = 3,
                            Salt = "zYszfTg4A0Kw/vODue5eHw==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EAlimentarPeces", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("alimentar_peces", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlAgua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_de_agua", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlElectrico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_electrico", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlEntorno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_de_entorno", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlHidroponico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_hidroponico", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.ERecirculacionAgua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("recirculacion_de_agua", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EComponenteLaboratorio", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EModuloComponente", "ModuloComponente")
                        .WithMany()
                        .HasForeignKey("ModuloComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUpa", "Upa")
                        .WithMany()
                        .HasForeignKey("UpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuloComponente");

                    b.Navigation("Upa");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ELaboratorio", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EComponenteLaboratorio", "ComponenteLaboratorio")
                        .WithMany()
                        .HasForeignKey("ComponenteLaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EProtocoloCOM", "TipoDeComunicacion")
                        .WithMany()
                        .HasForeignKey("TipoDeComunicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponenteLaboratorio");

                    b.Navigation("TipoDeComunicacion");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpaActividad", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EActividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUpa", "Upa")
                        .WithMany()
                        .HasForeignKey("UpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Upa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUsuario", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EEstadoUsuario", "EstadoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.ERol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("lestoma.Entidades.Models.ETokensUsuarioByAplicacion", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("AplicacionId")
                                .HasColumnType("integer")
                                .HasColumnName("aplicacion_id");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("fecha_creacion");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text")
                                .HasColumnName("creado_por_ip");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("expiracion");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text")
                                .HasColumnName("reeemplazado_por_token");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("fecha_revocacion");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text")
                                .HasColumnName("revocado_por_ip");

                            b1.Property<string>("Token")
                                .HasColumnType("text")
                                .HasColumnName("token");

                            b1.Property<int>("usuario_id")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("usuario_id");

                            b1.ToTable("tokens_usuario_por_aplicacion", "seguridad");

                            b1.WithOwner()
                                .HasForeignKey("usuario_id");
                        });

                    b.Navigation("EstadoUsuario");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EEstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ERol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
