// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lestoma.Data;

namespace lestoma.Data.Migrations
{
    [DbContext(typeof(LestomaContext))]
    partial class LestomaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("lestoma.Entidades.Models.EActividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_actividad");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("actividad", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(5169),
                            Ip = "172.30.96.1",
                            Nombre = "control de agua",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("4cc1a161-776c-48f5-8081-05343c247469"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(5193),
                            Ip = "172.30.96.1",
                            Nombre = "alimentacion de peces",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EAplicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NombreAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("TiempoExpiracionToken")
                        .HasColumnType("smallint")
                        .HasColumnName("tiempo_expiracion_token");

                    b.HasKey("Id");

                    b.ToTable("aplicacion", "seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreAplicacion = "App Movil",
                            TiempoExpiracionToken = (short)31
                        },
                        new
                        {
                            Id = 2,
                            NombreAplicacion = "Web",
                            TiempoExpiracionToken = (short)45
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Accion")
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("PKTabla")
                        .HasColumnType("text")
                        .HasColumnName("pk");

                    b.Property<string>("Schema")
                        .HasColumnType("text")
                        .HasColumnName("schema");

                    b.Property<string>("Session")
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("Tabla")
                        .HasColumnType("text")
                        .HasColumnName("tabla");

                    b.Property<string>("TipoDeAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<string>("UsuarioBD")
                        .HasColumnType("text")
                        .HasColumnName("user_bd");

                    b.HasKey("Id");

                    b.ToTable("auditoria", "seguridad");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EBuzon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("buzon", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EComponenteLaboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_id");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("JsonEstadoComponente")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("descripcion_estado");

                    b.Property<Guid>("ModuloComponenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_componente_id");

                    b.Property<string>("NombreComponente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_componente");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<Guid>("UpaId")
                        .HasColumnType("uuid")
                        .HasColumnName("upa_id");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("ModuloComponenteId");

                    b.HasIndex("UpaId");

                    b.ToTable("componente_laboratorio", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad50972d-6421-4853-ac04-2e33c7f01540"),
                            ActividadId = new Guid("4cc1a161-776c-48f5-8081-05343c247469"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 853, DateTimeKind.Local).AddTicks(8556),
                            Ip = "172.30.96.1",
                            JsonEstadoComponente = "{\"Id\":\"98a74bd5-7390-4244-8b2e-255d3707071d\",\"TipoEstado\":\"ON-OFF\",\"ByteHexaFuncion\":\"F0\",\"ByteDecimalFuncion\":240}",
                            ModuloComponenteId = new Guid("c1a18a89-4f8f-4d50-9279-93135483e329"),
                            NombreComponente = "BOMBA DE OXIGENO",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962")
                        },
                        new
                        {
                            Id = new Guid("9564116f-7904-4548-b99d-1e129c97441c"),
                            ActividadId = new Guid("4cc1a161-776c-48f5-8081-05343c247469"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 853, DateTimeKind.Local).AddTicks(8613),
                            Ip = "172.30.96.1",
                            JsonEstadoComponente = "{\"Id\":\"98a74bd5-7390-4244-8b2e-255d3707071d\",\"TipoEstado\":\"ON-OFF\",\"ByteHexaFuncion\":\"F0\",\"ByteDecimalFuncion\":240}",
                            ModuloComponenteId = new Guid("c1a18a89-4f8f-4d50-9279-93135483e329"),
                            NombreComponente = "LUZ ESTANQUE",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962")
                        },
                        new
                        {
                            Id = new Guid("4b78e7fb-fa05-4de4-837b-0b6b1fd689f8"),
                            ActividadId = new Guid("4cc1a161-776c-48f5-8081-05343c247469"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 853, DateTimeKind.Local).AddTicks(8623),
                            Ip = "172.30.96.1",
                            JsonEstadoComponente = "{\"Id\":\"98a74bd5-7390-4244-8b2e-255d3707071d\",\"TipoEstado\":\"ON-OFF\",\"ByteHexaFuncion\":\"F0\",\"ByteDecimalFuncion\":240}",
                            ModuloComponenteId = new Guid("c1a18a89-4f8f-4d50-9279-93135483e329"),
                            NombreComponente = "DOSIFICADOR DE ALIMENTO",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962")
                        },
                        new
                        {
                            Id = new Guid("a17c1b85-ad09-4208-9954-eb5b4b08ea13"),
                            ActividadId = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 853, DateTimeKind.Local).AddTicks(8628),
                            Ip = "172.30.96.1",
                            JsonEstadoComponente = "{\"Id\":\"f5f738c7-0dba-48ee-afea-b22530160653\",\"TipoEstado\":\"LECTURA\",\"ByteHexaFuncion\":\"0F\",\"ByteDecimalFuncion\":15}",
                            ModuloComponenteId = new Guid("c4425a21-86da-4cef-9623-28882135c403"),
                            NombreComponente = "TEMPERATURA H2O",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962")
                        },
                        new
                        {
                            Id = new Guid("dd162b75-cfac-47bf-8865-2eafabecc6a0"),
                            ActividadId = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 853, DateTimeKind.Local).AddTicks(8632),
                            Ip = "172.30.96.1",
                            JsonEstadoComponente = "{\"Id\":\"f5f738c7-0dba-48ee-afea-b22530160653\",\"TipoEstado\":\"LECTURA\",\"ByteHexaFuncion\":\"0F\",\"ByteDecimalFuncion\":15}",
                            ModuloComponenteId = new Guid("c4425a21-86da-4cef-9623-28882135c403"),
                            NombreComponente = "PH",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962")
                        },
                        new
                        {
                            Id = new Guid("7e0fe3e1-4e48-4aae-a833-4c8a1987bb12"),
                            ActividadId = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 853, DateTimeKind.Local).AddTicks(8635),
                            Ip = "172.30.96.1",
                            JsonEstadoComponente = "{\"Id\":\"f5f738c7-0dba-48ee-afea-b22530160653\",\"TipoEstado\":\"LECTURA\",\"ByteHexaFuncion\":\"0F\",\"ByteDecimalFuncion\":15}",
                            ModuloComponenteId = new Guid("c4425a21-86da-4cef-9623-28882135c403"),
                            NombreComponente = "NIVEL TANQUE",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962")
                        },
                        new
                        {
                            Id = new Guid("cbaad725-cacc-4ab1-b54e-91cb9414b953"),
                            ActividadId = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 853, DateTimeKind.Local).AddTicks(8639),
                            Ip = "172.30.96.1",
                            JsonEstadoComponente = "{\"Id\":\"c781773b-7d7c-47f7-b5d0-34a4943ba907\",\"TipoEstado\":\"AJUSTE\",\"ByteHexaFuncion\":\"F0\",\"ByteDecimalFuncion\":240}",
                            ModuloComponenteId = new Guid("48cc18e5-59cc-4c95-91fc-853ec233b225"),
                            NombreComponente = "SP_TEMPERATURA H2O",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962")
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EEstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("estado_usuario", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescripcionEstado = "verificar cuenta"
                        },
                        new
                        {
                            Id = 2,
                            DescripcionEstado = "Activado"
                        },
                        new
                        {
                            Id = 3,
                            DescripcionEstado = "Inactivo"
                        },
                        new
                        {
                            Id = 4,
                            DescripcionEstado = "Bloqueado"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ELaboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComponenteLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("componente_laboratorio_id");

                    b.Property<bool>("EstadoInternet")
                        .HasColumnType("boolean")
                        .HasColumnName("estado_internet");

                    b.Property<DateTime>("FechaCreacionDispositivo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_dispositivo");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.Property<int>("TipoDeComunicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_com_id");

                    b.Property<string>("TramaEnviada")
                        .HasColumnType("text")
                        .HasColumnName("trama_enviada");

                    b.Property<string>("TramaRecibida")
                        .HasColumnType("text")
                        .HasColumnName("trama_recibida");

                    b.Property<double?>("ValorCalculadoTramaEnviada")
                        .HasColumnType("double precision")
                        .HasColumnName("dato_trama_enviada");

                    b.Property<double?>("ValorCalculadoTramaRecibida")
                        .HasColumnType("double precision")
                        .HasColumnName("dato_trama_recibida");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteLaboratorioId");

                    b.HasIndex("TipoDeComunicacionId");

                    b.ToTable("detalle_laboratorio", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5738d6d-8dde-4b48-a0f0-2b2c2ffc54b9"),
                            ComponenteLaboratorioId = new Guid("ad50972d-6421-4853-ac04-2e33c7f01540"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(3115),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(2255),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 1,
                            TramaEnviada = "6FDAF029000000009834",
                            TramaRecibida = "49803CE33F8000008FC8",
                            ValorCalculadoTramaRecibida = 1.0
                        },
                        new
                        {
                            Id = new Guid("d558b2e6-0187-4fa9-99eb-cff4e6b87c2c"),
                            ComponenteLaboratorioId = new Guid("9564116f-7904-4548-b99d-1e129c97441c"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(4561),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(4552),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 2,
                            TramaEnviada = "495DF08E000000007B74",
                            TramaRecibida = "496D3C083F80000096D1",
                            ValorCalculadoTramaRecibida = 1.0
                        },
                        new
                        {
                            Id = new Guid("58cc3185-1867-41c3-99d8-d21f06a54b05"),
                            ComponenteLaboratorioId = new Guid("dd162b75-cfac-47bf-8865-2eafabecc6a0"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(4568),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(4567),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 1,
                            TramaEnviada = "493E0FA6000000007453",
                            TramaRecibida = "6FB2F0DC410E66663E8F",
                            ValorCalculadoTramaRecibida = 8.9000000000000004
                        },
                        new
                        {
                            Id = new Guid("0a87b909-c249-48c2-9541-f341114507bf"),
                            ComponenteLaboratorioId = new Guid("dd162b75-cfac-47bf-8865-2eafabecc6a0"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(4574),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(4573),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 1,
                            TramaEnviada = "493E0FA6000000007453",
                            TramaRecibida = "6FEFF08440D66666F1A3",
                            ValorCalculadoTramaRecibida = 6.7000000000000002
                        },
                        new
                        {
                            Id = new Guid("e4c74b36-b696-4164-91dd-40c50efe9001"),
                            ComponenteLaboratorioId = new Guid("cbaad725-cacc-4ab1-b54e-91cb9414b953"),
                            EstadoInternet = true,
                            FechaCreacionDispositivo = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(5011),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 854, DateTimeKind.Local).AddTicks(5003),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local",
                            TipoDeComunicacionId = 1,
                            TramaEnviada = "49F2F04541C00000A19A",
                            TramaRecibida = "6FEEF0D8434800001CA9",
                            ValorCalculadoTramaEnviada = 24.0,
                            ValorCalculadoTramaRecibida = 200.0
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EModuloComponente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_modulo");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("modulo_componente", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1a18a89-4f8f-4d50-9279-93135483e329"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 599, DateTimeKind.Local).AddTicks(3488),
                            Ip = "172.30.96.1",
                            Nombre = "ACTUADORES",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("c4425a21-86da-4cef-9623-28882135c403"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 599, DateTimeKind.Local).AddTicks(4894),
                            Ip = "172.30.96.1",
                            Nombre = "SENSORES",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("48cc18e5-59cc-4c95-91fc-853ec233b225"),
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 599, DateTimeKind.Local).AddTicks(4906),
                            Ip = "172.30.96.1",
                            Nombre = "SET_POINT/CONTROL",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EProtocoloCOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PrimerByteTrama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primer_byte_trama");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.ToTable("protocolo_com", "laboratorio_lestoma");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Peer to Peer",
                            PrimerByteTrama = "49",
                            Sigla = "PP"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Broad Cast",
                            PrimerByteTrama = "6F",
                            Sigla = "BS"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ERol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_rol");

                    b.HasKey("Id");

                    b.ToTable("rol", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreRol = "Super Administrador"
                        },
                        new
                        {
                            Id = 2,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            NombreRol = "Auxiliar"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ESuperAdministrador", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<short>("UsuarioId")
                        .HasColumnType("smallint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("super_administrador", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            UsuarioId = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            UsuarioId = (short)2
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("CantidadActividades")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad_actividades");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_upa");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<int>("SuperAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("superadmin_id");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.ToTable("upa", "superadmin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962"),
                            CantidadActividades = (short)5,
                            Descripcion = "queda ubicada en facatativá",
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(3151),
                            Ip = "172.30.96.1",
                            Nombre = "finca el vergel",
                            Session = "Anonimo",
                            SuperAdminId = 1,
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = new Guid("2ace840c-862b-4b32-b583-622587a8e06f"),
                            CantidadActividades = (short)2,
                            Descripcion = "queda ubicada en la universidad cundinamarca extensión faca",
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(3189),
                            Ip = "172.30.96.1",
                            Nombre = "ucundinamarca",
                            Session = "Anonimo",
                            SuperAdminId = 1,
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpaActividad", b =>
                {
                    b.Property<Guid>("UpaId")
                        .HasColumnType("uuid")
                        .HasColumnName("upa_id");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid")
                        .HasColumnName("actividad_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("UpaId", "ActividadId", "UsuarioId");

                    b.HasIndex("ActividadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("upa_actividad", "superadmin");

                    b.HasData(
                        new
                        {
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962"),
                            ActividadId = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            UsuarioId = 3,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(8260),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962"),
                            ActividadId = new Guid("4cc1a161-776c-48f5-8081-05343c247469"),
                            UsuarioId = 3,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(8278),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962"),
                            ActividadId = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            UsuarioId = 4,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(8282),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("91f86319-dea2-46d8-8c3d-2065b9297962"),
                            ActividadId = new Guid("4cc1a161-776c-48f5-8081-05343c247469"),
                            UsuarioId = 4,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(8284),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("2ace840c-862b-4b32-b583-622587a8e06f"),
                            ActividadId = new Guid("c071a713-b2d3-4dcf-be15-e3ca1a4d436b"),
                            UsuarioId = 5,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(8287),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            UpaId = new Guid("2ace840c-862b-4b32-b583-622587a8e06f"),
                            ActividadId = new Guid("4cc1a161-776c-48f5-8081-05343c247469"),
                            UsuarioId = 5,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 659, DateTimeKind.Local).AddTicks(8289),
                            Ip = "172.30.96.1",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoRecuperacion")
                        .HasColumnType("text")
                        .HasColumnName("codigo_recuperacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<DateTime>("FechaCreacionServer")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion_server");

                    b.Property<DateTime?>("FechaVencimientoCodigo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("vencimiento_codigo_recuperacion");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semilla");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<string>("TipoDeAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_aplicacion");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario", "usuarios");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Apellido = "Lestoma-APP",
                            Clave = "vXbhVJqYXTKJhsUfgepmlREF3WZXVNRFSFVkDrIxQaI=",
                            Email = "diegop177@hotmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 644, DateTimeKind.Local).AddTicks(1054),
                            Ip = "172.30.96.1",
                            Nombre = "Diego-Super",
                            RolId = 1,
                            Salt = "9NFnwgZRTJr61A3ymVq4sA==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 1,
                            Apellido = "Movil",
                            Clave = "vXbhVJqYXTKJhsUfgepmlREF3WZXVNRFSFVkDrIxQaI=",
                            Email = "lestomaudecmovil@gmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 643, DateTimeKind.Local).AddTicks(7621),
                            Ip = "172.30.96.1",
                            Nombre = "Lestoma-APP",
                            RolId = 1,
                            Salt = "9NFnwgZRTJr61A3ymVq4sA==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Lestoma",
                            Clave = "A5HzwpwJIuYyDvaDL1RFes/ORX7PUmnU+LSGK8hChXc=",
                            Email = "diegoarturo1598@hotmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 651, DateTimeKind.Local).AddTicks(1435),
                            Ip = "172.30.96.1",
                            Nombre = "Administrador",
                            RolId = 2,
                            Salt = "3CM+4ymQ6qe0KqrKndcRBw==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Lestoma",
                            Clave = "Z2Ykx/Ilz7kLhisdZNSl3YVQIJLM2fP6QII/WrXPKhU=",
                            Email = "programadoresuc@outlook.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 658, DateTimeKind.Local).AddTicks(4479),
                            Ip = "172.30.96.1",
                            Nombre = "Auxiliar 1",
                            RolId = 3,
                            Salt = "nl4cgYNV4yg9BRw070b4vw==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Lestoma",
                            Clave = "Z2Ykx/Ilz7kLhisdZNSl3YVQIJLM2fP6QII/WrXPKhU=",
                            Email = "tudec2020@gmail.com",
                            EstadoId = 2,
                            FechaCreacionServer = new DateTime(2023, 2, 1, 14, 45, 58, 658, DateTimeKind.Local).AddTicks(4511),
                            Ip = "172.30.96.1",
                            Nombre = "Auxiliar 2",
                            RolId = 3,
                            Salt = "nl4cgYNV4yg9BRw070b4vw==",
                            Session = "Anonimo",
                            TipoDeAplicacion = "Local"
                        });
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EAlimentarPeces", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("alimentar_peces", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlAgua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_de_agua", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlElectrico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_electrico", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlEntorno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_de_entorno", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.EControlHidroponico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("control_hidroponico", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.ModelsReports.ERecirculacionAgua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnteriorRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("anterior_registro_id");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<Guid>("DetalleLaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("detalle_laboratorio_id");

                    b.HasKey("Id");

                    b.ToTable("recirculacion_de_agua", "reportes");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EComponenteLaboratorio", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EActividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EModuloComponente", "ModuloComponente")
                        .WithMany()
                        .HasForeignKey("ModuloComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUpa", "Upa")
                        .WithMany()
                        .HasForeignKey("UpaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("ModuloComponente");

                    b.Navigation("Upa");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ELaboratorio", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EComponenteLaboratorio", "ComponenteLaboratorio")
                        .WithMany()
                        .HasForeignKey("ComponenteLaboratorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EProtocoloCOM", "TipoDeComunicacion")
                        .WithMany()
                        .HasForeignKey("TipoDeComunicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponenteLaboratorio");

                    b.Navigation("TipoDeComunicacion");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUpaActividad", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EActividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUpa", "Upa")
                        .WithMany()
                        .HasForeignKey("UpaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.EUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Upa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EUsuario", b =>
                {
                    b.HasOne("lestoma.Entidades.Models.EEstadoUsuario", "EstadoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("lestoma.Entidades.Models.ERol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("lestoma.Entidades.Models.ETokensUsuarioByAplicacion", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("AplicacionId")
                                .HasColumnType("integer")
                                .HasColumnName("aplicacion_id");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("fecha_creacion");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text")
                                .HasColumnName("creado_por_ip");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("expiracion");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text")
                                .HasColumnName("reeemplazado_por_token");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("fecha_revocacion");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text")
                                .HasColumnName("revocado_por_ip");

                            b1.Property<string>("Token")
                                .HasColumnType("text")
                                .HasColumnName("token");

                            b1.Property<int>("usuario_id")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("usuario_id");

                            b1.ToTable("tokens_usuario_por_aplicacion", "seguridad");

                            b1.WithOwner()
                                .HasForeignKey("usuario_id");
                        });

                    b.Navigation("EstadoUsuario");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.EEstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("lestoma.Entidades.Models.ERol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
